- name: Install Cilium CNI
  ansible.builtin.shell: |
    cilium install --version 1.16.3 \
      --set=ipam.operator.clusterPoolIPv4PodCIDRList="10.42.0.0/16"
  args:
    creates: /usr/local/bin/cilium

- name: Enable Hubble
  ansible.builtin.command: cilium hubble enable
  register: cilium_hubble_result
  changed_when: "'already enabled' not in cilium_hubble_result.stdout"
