- name: Check if dphys-swapfile service exists
  ansible.builtin.stat:
    path: /etc/systemd/system/dphys-swapfile.service
  register: common_dphys_service

- name: Stop dphys-swapfile service
  ansible.builtin.service:
    name: dphys-swapfile
    state: stopped
    enabled: no
  when: common_dphys_service.stat.exists

- name: Remove dphys-swapfile package
  ansible.builtin.apt:
    name: dphys-swapfile
    state: absent
    purge: yes
  when: ansible_os_family == "Debian"

- name: Verify swap is disabled
  ansible.builtin.command: swapon --summary
  register: common_swap_status
  changed_when: false

- name: Fail if swap is still active
  ansible.builtin.fail:
    msg: "Swap is still active! Please check manually."
  when: common_swap_status.stdout != ""

