---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Stop dphys-swapfile service
  ansible.builtin.service:
    name: dphys-swapfile
    state: stopped
    enabled: false
  when: "'dphys-swapfile.service' in ansible_facts.services"

- name: Remove dphys-swapfile package
  ansible.builtin.apt:
    name: dphys-swapfile
    state: absent
    purge: true
  when: ansible_os_family == "Debian"

- name: Verify swap is disabled
  ansible.builtin.command: swapon --summary
  register: common_swap_status
  changed_when: false

- name: Fail if swap is still active
  ansible.builtin.fail:
    msg: "Swap is still active! Please check manually."
  when: common_swap_status.stdout != "" | trim != ""
