---
- name: Ensure flux namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: flux-system
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
  when: not ansible_check_mode

- name: Download Flux manifests
  ansible.builtin.get_url:
    url: https://github.com/fluxcd/flux2/releases/tag/v2.7.2/download/install.yaml
    dest: /tmp/install.yaml
    mode: '0644'
  delegate_to: localhost
  check_mode: false

- name: Apply Flux manifests via kubernetes.core.k8s
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    state: present
    src: /tmp/install.yaml
  when: not ansible_check_mode

- name: exit if token is not provided
  ansible.builtin.fail:
    msg: "flux_git_token variable is not defined. Please provide a GitHub token with repo access."
  when: flux_git_token is not defined
  check_mode: false

- name: Create GitHub token secret
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: flux-system
        namespace: flux-system
      type: Opaque
      stringData:
        token: "{{ flux_git_token }}"
  when: not ansible_check_mode

- name: Create GitRepository resource
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    state: present
    definition:
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        interval: 1m
        url: "https://github.com/sfotiadis/flux-rpi-cluster"
        branch: "main"
  when: not ansible_check_mode

- name: Create Kustomization to sync Git repository
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    state: present
    definition:
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        interval: 1m
        path: "./clusters/{{ cluster_name }} }}"
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
  when: not ansible_check_mode
