---
- name: Check if Helm is installed
  ansible.builtin.command:
    cmd: helm version --short
  register: master_helm_check
  ignore_errors: true
  changed_when: false


- name: Download Helm binary if not installed
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz"
    dest: "/tmp/helm-{{ helm_version }}.tar.gz"
    mode: '0644'
  when: master_helm_check.failed

- name: Extract Helm
  ansible.builtin.unarchive:
    src: "/tmp/helm-{{ helm_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: true
    creates: "/tmp/linux-arm64/helm"
  when: master_helm_check.failed

- name: Move Helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/linux-arm64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  become: true
  args:
    creates: /usr/local/bin/helm
  when: master_helm_check.failed

- name: Verify Helm installation
  ansible.builtin.command:
    cmd: helm version --short
  register: master_helm_installed
  changed_when: false
